### PR TITLE
Automated Contributor's List 

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
We Can Update Contributor's List Automatically By using [this](https://allcontributors.org/)

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
@Team-thedatatribune it is not working properly, please check their docs, [here](https://allcontributors.org/)
)

**Comment by Team-thedatatribune** [comment]
> @Team-thedatatribune it is not working properly, please check their docs, [here](https://allcontributors.org/)
> )

Yeah exactly, we've been trying to debug the same tho' it's failing to work along with the expactations...  
    
It would be great if you can check the issue behind :))

**Comment by Siddhant-K-code** [comment]
ok, i will check it, and try it to debug @Team-thedatatribune

**Comment by Team-thedatatribune** [comment]
@Siddhant-K-code We think it's working now...  
Can you please varify once?

**Comment by Siddhant-K-code** [comment]
@Team-thedatatribune Yes, It's Working Now.

**Pull request merged**
