### PR TITLE
Updated Contributors.md

### PR DESCRIPTION
**Pull request by ravi-prakash1907**
Updating the contributors' markdown #5

### CODE REVIEW

**Comment by Team-thedatatribune** [comment]
@all-contributors please add @ravi-prakash1907  for content

**Comment by ravi-prakash1907** [comment]
@all-contributors please add @ravi-prakash1907 for content

**Comment by Team-thedatatribune** [comment]
@all-contributors please add @kraken-sudo for content

**Comment by Team-thedatatribune** [comment]
@all-contributors please add @ravi-prakash1907 for content, data, code, design

**Pull request merged**
